### ISSUE TITLE
[ITEMS] New Action type for Items - 'Starship Combat Action'

### ISSUE THREAD

**Issue by JayBWalker** [foundryvtt-starfinder/foundryvtt-starfinder#168]
As titled. I've been using 'Full Action' for now, as a placeholder.

**Comment by TimToxopeus** [comment]
I am not 100% sure I understand the intention here. We have recently introduced actual starship actions, is this request related to those, still relevant, or superceded by them?

**Comment by JayBWalker** [comment]
What's been done is great but I worry that it is too difficult to homebrew additional actions and/or edit the existing ones if need be. Which is why I originally suggested it as a unique Item Type.

**Comment by TimToxopeus** [comment]
Okay, gotcha. Yeah, they actually are implemented as a unique item type, it's just not easily doable to edit them or create new ones. I started implementing a custom starship actions interface, but it is a very complicated data structure, especially thanks to SOM adding lots of new layers of complexity to starship actions. So that will take me a while.

Editing the existing ones is also difficult because they are automatically pulled in from the starship compendium, rather than actually owned by the starship actor itself. That means they are essentially read-only.

You can edit the starship compendium and create a local copy of it instead, and make your world point to that one, under the System Settings there is a new field called "Starship Actions Source Compendium", change that to make it point to your custom compendium.

**Comment by JayBWalker** [comment]
That's all fair. Good to know that there is plans for this.
My only concern lies in the ability for non-coders to homebrew their own Starship Combat Rules (or tweak the existing ones), and to continue supporting the non-coder homebrew experience overall.
