### ISSUE TITLE
[Bug] Skill constant modifier disappears if a roll formula modifier exists of the same type

### ISSUE THREAD

**Issue by supernovajm** [foundryvtt-starfinder/foundryvtt-starfinder#278]
Expected Behavior:
Skill Modifiers of modifier type "Constant" should always display in the skill sheet, and should be applied if they are the highest available bonus of that type (ex: insight).

Actual Behavior:
Skill bonuses that are "constant" will not be displayed on the sheet AND will not be used in the roll if a higher "roll modifier" bonus of the same type exists. Even if the roll modifier is not enabled, the constant bonus will not be applied.

Example:
Operative with +2 insight bonus from Operative's Edge. 
![image](https://user-images.githubusercontent.com/24704061/107424567-d5b1f300-6aeb-11eb-9d1e-f73d89ba1ab8.png)

They have an Exploit "Trap Spotter" that doubles their insight bonus for perception checks against traps. **Note that the bonus is not even enabled.** The fact that it exists is enough to cause this problem.
![image](https://user-images.githubusercontent.com/24704061/107424600-de0a2e00-6aeb-11eb-95de-4f0c2eb9b413.png)

They should have a +11 normally, and a +13 when checking for traps. But the sheet only gives them a +9, not counting the constant insight bonus.
![image](https://user-images.githubusercontent.com/24704061/107424621-e4000f00-6aeb-11eb-8b8f-335d7de73b07.png)

Rolling **without** adding the Trap Spotter bonus rolls with a +9 (missing the +2 constant insight bonus)
![image](https://user-images.githubusercontent.com/24704061/107424741-04c86480-6aec-11eb-9c00-0083563cae3e.png)

If you set the Trap Spotter bonus to be +2 or less (equal or less than the constant bonus from operative's edge), the constant bonus is properly displayed on the skill sheet again.
![image](https://user-images.githubusercontent.com/24704061/107425062-7acccb80-6aec-11eb-9fb3-e4c6d22c1a7a.png)
![image](https://user-images.githubusercontent.com/24704061/107425065-7c968f00-6aec-11eb-93db-c630361bb665.png)

**Comment by Ekky-VTT** [comment]
Hello,
I can add some input in this bug - because I think my behavior is really close to it : 
I am creating an operative too. I have added the Operative's Edge (+2 insight on all skills) that works on a "normal" skill : 
![image](https://user-images.githubusercontent.com/83665201/117050252-70018b80-ad15-11eb-8369-5448838ce58e.png)
When I add the "Skill Focus" feat on the two "Hacker's specialization" related skills (computers and engineers), the bonus is only applied to "Engineering" but not "Computers".
![image](https://user-images.githubusercontent.com/83665201/117050737-00d86700-ad16-11eb-8f4f-c6e5e00317ae.png)
Moreover, the Operative's Edge bonus is not applied on "Computers" too.
![image](https://user-images.githubusercontent.com/83665201/117050858-27969d80-ad16-11eb-82cd-d30487907a19.png)
The Engineers skill is well updated.
![image](https://user-images.githubusercontent.com/83665201/117050992-53b21e80-ad16-11eb-93bf-18a764ba4e82.png)

I have tested with a single Skill Focus and two different ones but the problem remains.

**Comment by Ekky-VTT** [comment]
Hello,
Ok, now I understand why my +3 Insight bonus doesn't apply on my Computers Skill, it's because of this bonus I was so proud to generate (I am using your module for 2 days only ;))
![image](https://user-images.githubusercontent.com/83665201/117053723-975a5780-ad19-11eb-8661-2d0d906a825d.png)

BTW, please keep going, your module is excellent

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
