### ISSUE TITLE
Issues Rolling with Solarian Weapons

### ISSUE THREAD

**Issue by Shwaazi** [foundryvtt-starfinder/foundryvtt-starfinder#309]
Unfortunately it appears there is no Solarian weapons, or Solarian weapon crystals. As such, when making a New Custom weapon using the add button in the inventory, it appears some things don't work properly. When using the roll damage with attack roll configuration option, it will not actually function properly. Is there some other way to add a Solarian weapon/crystal I am missing? Or a way to create the item properly? 

Also, is there a way to just make Attacks and Damage roll together in the same window? Or is this possibly in the works?

Thank you for the time and effort you put into all this!

**Comment by Shwaazi** [comment]
This appears to be an issue with weapons without a capacity/charges/ammunition in particular. Without it, it will only roll attack rolls, not damage rolls alongside them with the system option on.

**Comment by ThroughlyDruxy** [comment]
I just added all solarian weapon crystals from all but Armory (it's coming) as hybrid items. You should be able to drag the crystal onto the solar weapon and it will have the extra damage applied when equipped.

The reason there are no Solarian weapons is because solarian manifestations can take any form. 

>Without it, it will only roll attack rolls, not damage rolls alongside them with the system option on.
Did you add a damage field on the weapon? Unless you specify damage to roll, it won't show an option to roll damage.

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
