### ISSUE TITLE
lookupRange formulas in modifiers lead to incorrect bonus stacking

### ISSUE THREAD

**Issue by LebombJames** [foundryvtt-starfinder/foundryvtt-starfinder#530]
Another entry in the bonus type stacking saga 😛

https://aonsrd.com/Disciplines.aspx?ID=44
`lookupRange(@skills.acr.ranks,  (@abilities.con.mod+@resources.vanguard.entropicPool.value), 1, 0)`

This formula adds Con+EP to Acrobatics if the actor has no ranks (as a constant modifier). This works as expected until you make a smaller constant insight modifier (+2 for example).

With the above +2, if Con+EP is bigger, it applies it when at 0 ranks. If it's *smaller* it applies neither. (Tried it again a second time and it *always* applied the +2, even when Con+EP was bigger? Something odd is going on)

At 1 rank: it works as expected, but it's previously added neither.

Iankid found that the modifier needs to be saved in order for things to update, but I haven't investigated that properly.

**Comment by Iankid** [comment]
The Modifier needing to be save to update, seems to be needed only when the insight bonus switches from a static value bonus, to a formula bonus. 
i.e. +2 insight and +@abilities.con.mod+@resources.vanguard.entropicPool.value Insight.

If the insight bonus is set to the formula, it can update in realtime as expect. It however stays using that formula, despite if the value goes under the +2 static insight. This is fixed by going to either modifier and saving them.
The reverse is true. if it's using the static value, but the formula would output a higher value, you need to save either modifier.

**Comment by Iankid** [comment]
As an addition to this. it seems 2 situational insight bonuses, where one is a formula, doesn't place the formula bonus in the situational selections

**Comment by LebombJames** [comment]
Closed by #880 🥳
