### ISSUE TITLE
DR modifier improvements

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#724]
Currently DR is set to block the specified damage value of all damage rolls, except if containing the specified attribute.
This works for DR 10/Slashing and you're using a slashing weapon to get through. Along with other similar examples.
However there are plenty of player and item options that provide DR Against a specific attribute. Example, DR 5 against slashing. This would protect the character against slashing weapons in particular.

Currently the DR modifier does not have an option to protect against one specific source, And the presence of multiple physical damage types outputs an incorrect reduction.
A DR 5 against 10 slashing and bludgeoning is completely reducing the 10 damage currently. As I think it's reducing each damage type, rather then the total.

**Comment by wildj79** [comment]
There are a couple of things going on here that need to be addressed. 

1) The current implementation is only working partially. It only takes a single item of negation into consideration. RAW, there can be "and" or "or" clauses in the negated by field. `DR 5/bludgeoning or piercing` or `DR 5/magic and lawful` for example (the first example is how your first use case should be handled, it just won't work with the current implementation).

2) Your second point is actually working RAW. When you roll for damage and there are multiple damage types, you're supposed to split the damage evenly between the damage types. In your example, that would mean that the attack is doing 5 points of slashing  and 5 points of bludgeoning. Damage reduction affects _all_ kinetic damage types unless negated. When applying damage, you consider each source of damage separately. So, you check the first 5 slashing damage and see that it's being affected by damage reduction. Then the next 5 bludgeoning damage and see that it's reduced by damage reduction as well, effectively taking the total damage down to 0.

So, the first issue is definitely something that needs to be addressed. How negation is handled needs to be tweaked to allow for multiple negation clauses on a source of DR. The second issue is gonna be a "wont fix", since it's working rules as written.

**Comment by Iankid** [comment]
Closed in favor of more concise list of issues
